# Generated by Django 5.1.4 on 2025-01-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('user', '0005_remove_user_gender_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default='R02', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.role'),
        ),
    ]
