# Generated by Django 5.1.4 on 2025-01-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_gender_id_remove_role_id_and_more'),
        ('user', '0006_user_gender_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default='R02', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role', to='tables.role'),
        ),
    ]
